import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import localFont from 'next/font/local'

const splatFont = localFont({ src: './../../public/fonts/Splatfont2.ttf' })

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={splatFont.className}>
        <header className='bg-black_with_opacity'>
          <div className='flex items-center justify-between ml-4 mr-4 sm:justify-start'>
            <Image
              priority
              src="/images/soul_cup.png"
              width={75}
              height={75}
              alt='Logo de la Soul Cup'
            />

            <Image
              priority
              src="/images/mobile/hamburger_mobile.svg"
              width={35}
              height={35}
              alt='Hamburger button to access menu'
              className='sm:hidden'
            />

              <nav className=' hidden ml-4 sm:flex sm:w-[100%]'>
                <ul className='flex gap-x-6 grow'>
                  <li className='text-white grow text-center'>Soul League</li>
                  <li className='text-white grow text-center'>Liste des équipes</li>
                  <li className='text-white grow text-center'>Liste des joueurs</li>
                  <li className='text-white grow text-center'>Tournois</li>
                  <li className='text-white grow text-center'>A propos</li>
                </ul>
              </nav>
          </div>

        </header>
        {children}

      </body>
    </html>
  )
}
